### ISSUE TITLE
npm install mern-cli failed

### ISSUE THREAD

**Issue by loserdong** [Hashnode/mern-cli#20]
error stack from npm-debug.log

```
5 verbose addRemoteGit caching github:timoxley/next-tick#0.0.2
626 verbose addRemoteGit timoxley/next-tick#0.0.2 is a repository hosted by github
627 silly tryGitProto attempting to clone git://github.com/timoxley/next-tick.git#0.0.2
628 silly tryClone cloning timoxley/next-tick#0.0.2 via git://github.com/timoxley/next-tick.git#0.0.2
629 verbose tryClone git-github-com-timoxley-next-tick-git-0-0-2-636565fd not in flight; caching
630 verbose correctMkdir /Users/dw/.npm/_git-remotes correctMkdir not in flight; initializing
631 info git [ 'config', '--get', 'remote.origin.url' ]
632 verbose stack TypeError: Bad argument
632 verbose stack     at ChildProcess.spawn (internal/child_process.js:289:26)
632 verbose stack     at exports.spawn (child_process.js:385:9)
632 verbose stack     at exports.execFile (child_process.js:148:15)
632 verbose stack     at execGit (/usr/local/lib/node_modules/npm/lib/utils/git.js:23:10)
632 verbose stack     at /usr/local/lib/node_modules/npm/lib/utils/git.js:45:5
632 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:88:20
632 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
632 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
632 verbose stack     at FSReqWrap.oncomplete (fs.js:111:15)
633 verbose cwd /Users/dw/Workspace/me
634 error Darwin 15.6.0
635 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "mern-cli"
636 error node v7.0.0
637 error npm  v3.10.8
638 error Bad argument
639 error If you need help, you may report this error at:
639 error     <https://github.com/npm/npm/issues>
640 verbose exit [ 1, true ]
```

**Comment by houssem-yahiaoui** [comment]
This is certainly wierd, @loserdong are still having the same error ?

**Comment by loserdong** [comment]
It's ok, I will close the question.
