### ISSUE TITLE
error starting project

### ISSUE THREAD

**Issue by ravi100k** [Hashnode/mern-cli#23]
[nodemon] watching 14 files
MERN is running on port: 8000! Build something amazing!
Please make sure Mongodb is installed and running!

H:\hybrid\mernio\myApp\node_modules\mongodb\lib\server.js:265
        process.nextTick(function() { throw err; })
                                      ^
MongoError: failed to connect to server [localhost:27017] on first connect
    at Pool.<anonymous> (H:\hybrid\mernio\myApp\node_modules\mongodb-core\lib\to
pologies\server.js:326:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (H:\hybrid\mernio\myApp\node_modules\mongodb-core\
lib\connection\pool.js:270:12)
    at Connection.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (H:\hybrid\mernio\myApp\node_modules\mongodb-core\lib\
connection\connection.js:175:49)
    at Socket.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by ajsobek** [comment]
You need to install and run MongoDB on your local machine

**Comment by mannyhenri** [comment]
All being worked on with! So when you generate a new project with the mern-cli tool it will reflect where [the starter repo is!](https://github.com/Hashnode/mern-starter)
